export const ATILA_PROJECT_HTML = `
<img _ngcontent-c12="" class="center-block" style="max-height: 100%;max-width: 100%" src="https://i0.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/atila-tech-stack.png?resize=700%2C436">
    <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">At <a href="https://atila.ca/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Atila</a>, we’re trying to provide all students with access to funding for a quality education. This is a big problem with many moving parts and the challenges can be very complex. This article will give you an idea of the software stack we use to solve this problem and some advice on how to choose a software stack for your company as well.</p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;"> </p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Table of Contents</p>
        <ul style="margin: 0px 0px 1.5em 1.5em; padding: 0px; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">
          <li>High-Level Architecture</li>
          <li>Design Principles
            <ul style="margin: 0px 0px 0px 1.5em; padding: 0px;">
              <li>Decentralization</li>
              <li>Progressive Web Apps</li>
            </ul>
          </li>
          <li>Front End
            <ul style="margin: 0px 0px 0px 1.5em; padding: 0px;">
              <li>Why Angular and not React?</li>
            </ul>
          </li>
          <li>Back End
            <ul style="margin: 0px 0px 0px 1.5em; padding: 0px;">
              <li>Why Python Django and not Ruby on Rails?</li>
            </ul>
          </li>
          <li>Infrastructure</li>
          <li>Next Steps
            <ul style="margin: 0px 0px 0px 1.5em; padding: 0px;">
              <li>LISP</li>
              <li>We Need Better Devops</li>
              <li>Inexperience With People and Project Management</li>
              <li>More Machine Learning Please</li>
            </ul>
          </li>
          <li>Conclusion</li>
        </ul>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">What is Atila?</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;"><a href="https://atila.ca/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Atila</a> is a platform that allows students to <a href="atila/what-is-atila" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">automatically find and apply</a> to scholarships all in one click, all from one site. We automate many different types of scholarship applications from web to pdfs and we try to automate the entire application process (finding the scholarships, filling the forms and even <a href="https://www.youtube.com/watch?v=c_K4342WMwQ" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">writing the email</a> ). We also have a platform for students to post <a href="blog/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">blogs</a> and <a href="forum/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">forums</a>, allowing them to share information and advice on school, career and life topics.</p>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">High-Level Architecture</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Atila’s front end is a <a href="https://developers.google.com/web/progressive-web-apps/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Progressive Web App</a> built on the <a href="https://angular.io/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Angular Framework</a>. The frontend is partially serverless through the use of Firebase Cloud Functions. The backend is a RESTful API built on <a href="https://www.djangoproject.com/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Python’s Django</a> Framework and served over the <a href="http://www.django-rest-framework.org/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Django REST Framework</a>. The core database is a PostgreSQL database. The infrastructure is a combination of Amazon Web Services (AWS) and Google Cloud Platform (GCP) services.</p>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">Design Principles</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">While building Atila, we tried to establish some high-level design principles which drive the decisions that we make.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">Decentralization</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">We try to design the various services powering to Atila run as independently as possible. This means that our front end app and our backend app are completely independent of each other and could theoretically be run as two seperate companies. The <a href="https://12factor.net/" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">12 Factor App</a> was an inspiration behind how we thought about building our application.</p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Another really interesting post we stumbled across just before publishing this article is <a href="https://plus.google.com/+RipRowan/posts/eVeouesvaVX" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Steve Yegge’s rant</a> on Amazon and Google Platforms. Steve mentions how Jeff Bezos asked for all services at Amazon to be designed as if they would be externalized to outside developers and inter process communications would be done through service interfaces. The rant sounds slightly peculiar, but it really changes the way you think about designing systems. This may be the most influential paper on system architecture design I have ever read.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">Progressive Web Apps</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">At Atila we believe that despite the current prevalence of mobile apps, web apps will prove to be the best choice for many software companies moving forward:</p>
        <ol style="margin: 0px 0px 1.5em 1.5em; padding: 0px; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">
          <li>People are increasingly reluctant to download a new app from the app store.  “Downloading” a web app is simply a matter of entering a few letters into a URL.
            <ol style="margin: 0px 0px 0px 1.5em; padding: 0px;">
              <li>As a startup you don’t want to lose because no one wants to download your app before they can even find out if its good or bad.</li>
            </ol>
          </li>
          <li>As browsers become more powerful, web apps are able to offer the same power, speed and features as native apps.</li>
          <li>Less reliance on the gatekeepers Android and Apple, and their app review process.</li>
          <li>A single codebase and ability to roll out on all devices and operating systems.</li>
          <li>A common advantages people say mobile apps have is higher engagement, this is usually due to native app features like push notifications, offline support and home screen placement; with progressive apps, these features are now becoming available on web apps.</li>
        </ol>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">Front End</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Our front end is a Progressive Web App built on the Angular Framework.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">Why Angular and not React?</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Choosing Angular as our front end framework is essentially a bet on the jockey and not necessarily the horse. Google is arguably the main private company that is driving many architectural decisions regarding the future of the internet. If we wanted to build an internet startup, it makes sense to use the tools and strategies created and recommended by the company which understands the internet best. It’s reassuring to see that <a href="https://www.madewithangular.com/categories/google" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">many Google sites are using Angular</a>, though its a bit off-putting that so many of them still use Angularjs. Though Angular's strentgh also ends up being its weakness. </p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Angular is a framework and not a library, so it has a very opinionated way of doing some things. While the Google/Angular team is very competent and generally very supportive of the developer community; frankly, we would still rather let the open source community decide the best way to build certain things than follow the edicts of one company.</p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Material Design also has a lot of HTML bloat, so simple things like a text input field will use about 3 different custom elements nested within it, none of which you can actually edit in your IDE and is only visible after you build the app in your browser.</p>
        <figure class="wp-caption aligncenter" id="attachment_202" style="margin: 0px auto 1.7em; clear: both; color: #999999; font-size: 17.5px; font-style: italic; max-width: 2000px; font-family: 'Source Sans Pro', serif;"><a data-slb-active="1" data-slb-asset="1586910769" data-slb-group="200" data-slb-internal="0" href="https://i1.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank"><img alt="" aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}"="" class="wp-image-202 size-full" data-attachment-id="202" data-comments-opened="1" data-image-description="" data-image-meta="{" data-image-title="angular-material-html-bloat" data-large-file="https://i1.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?fit=700%2C318" data-medium-file="https://i0.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?fit=300%2C136" data-orig-file="https://i0.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?fit=2000%2C909" data-orig-size="2000,909" data-permalink="http://blog.tomiwa.ca/building-atila-essential-software-startup-tech-stack/angular-material-html-bloat/" height="318" sizes="(max-width: 700px) 100vw, 700px" src="https://i2.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?resize=700%2C318" srcset="https://i0.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?w=2000 2000w, https://i1.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?resize=300%2C136 300w, https://i2.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?resize=768%2C349 768w, https://i2.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?resize=700%2C318 700w, https://i1.wp.com/blog.tomiwa.ca/wp-content/uploads/2018/03/angular-material-html-bloat.png?w=1400 1400w" style="border: 0px; height: auto; max-width: 100%; vertical-align: middle; display: block; margin: 0.4em auto 0px;" width="700"/></a>
          <figcaption class="wp-caption-text" style="text-align: center; margin: 0.9em 0px;">A “Simple” form field in Angular Material</figcaption>
        </figure>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">When choosing any software to use, a major benefit is the community support. React (<a href="https://github.com/facebook/react/stargazers" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">91K github stars</a>) is way more popular than Angular (<a href="https://github.com/angular/angular/stargazers" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">34K github stars</a>) and seems to be getting more popular by the day. This is something we sometimes worry about and ask ourselves if we are missing the React rocket ship that might be about to take off.</p>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">Back End</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Our backend is a RESTful API built on Python’s Django Framework and served over the Django REST framework.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">Why Python Django and not Ruby on Rails?</span></h3>
        <blockquote style="color: #777777; font-style: italic; margin: 0px 0px 2.4em; padding: 12px 0px 0px 44px; position: relative; font-family: 'Source Sans Pro', serif; font-size: 20px;">
          <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">The upper bound of a framework’s power, is approximately the upper bound of the language’s power.</p>
        </blockquote>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;"><br/>Similar to Angular vs. React, we chose to bet on the jockey and not the horse. However, now the jockey is the programming language. Python is a more ubiquitous programming language than Ruby and in our opinion, more powerful. If you were to analyze the upper bound of a framework’s power, its an approximation of the upper bound of the language’s power. </p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;"> </p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">We also plan on significantly developing machine learning and data science capabilities into various products. For example,  more intelligent scholarship recommendations and improving the automation engines. Python also offers more libraries and community support for these more scientifically rigorous tasks.</p>
        <blockquote style="color: #777777; font-style: italic; margin: 0px 0px 2.4em; padding: 12px 0px 0px 44px; position: relative; font-family: 'Source Sans Pro', serif; font-size: 20px;">
          <p style="margin: 0px 0px 1.5em;">Good systems design beats good frameworks.</p>
        </blockquote>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Finally, we try to heed the aphorism of“good systems design beats good frameworks”. So there’s a case to be made that it doesn’t actually matter that much what framework we pick, as long as we build a well engineered system. With that being said, we never let logic get in the way of a good blog post.</p>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">Infrastructure</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Our frontend is hosted with static files and a CDN that is a combination of GCP and firebase hosting and AWS S3. We have a special dockerized Google App Engine instance for some server side rendering to help with SEO.</p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;"> </p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Our backend infrastructure is hosted on AWS EC2/Heroku instances with PostgreSQL as our relational data store. We also store some analytics and event data in a Firebase nosql database and use REDIS’ in-memory data store as the communication layer for our websockets real time automation notifications.</p>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">We use a combination of Sentry, New Relic and Logentries for error reporting and performance management and Sendgrid for programmatic emails.</p>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">Next Steps</span></h2>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">LISP</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">New engineers to Atila are recommended to read Paul Graham’s <a href="https://www.amazon.com/Hackers-Painters-Big-Ideas-Computer/dp/1449389554" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Hackers and Painters</a> book and the <a href="http://www.paulgraham.com/articles.html" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">essays on his blog</a>. A particularly inspirational one for us was <a href="http://www.paulgraham.com/avg.html" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">Beating the Averages</a>. One of the key points in the article is that smart startups should write their code in LISP. We also found that LISP is very popular within academia and machine learning research, which makes it even more appealing to us. After much research and discussion we are planning on rolling out some features for the site in LISP and specifically looking at the Clojure dialect.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">We Need Better Devops</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">A space that we need to get better at is devops. We need to be more disciplined about slightly slowing down on shipping new features (gasp) and making sure we’re allocating time to paying off technical debt and making our engineers more efficient and productive. Tools like travis CI, Jenkins CD, GraphQL and Github Webhooks are things we’ve been eyeing from a distance but truthfully, we should probably be trying harder to integrate these tools.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">Inexperience With People and Project Management</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">As the company grows we are also thinking about how we can most effectively handle project management and our team and culture at scale. Most of our team are still students so we don’t actually have a lot of experience with this. We are currently looking at things like Asana and even looking at development methodologies like Agile but still don’t really understand it. If you have any advice on either project and people management for startups, please let us know.</p>
        <h3 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.563rem; margin-bottom: 1em; margin-top: 1.5em;"><span style="font-weight: 400;">More Machine Learning Please</span></h3>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">We are also planning on devoting more time towards adding machine learning capabilities in more products on our site. The key use cases we are currently looking at include serving more personalized and useful information to our users and making the automation engine more robust. A common debate we have internally is build vs. buy. While we want to move quickly and use proven solutions, there is an argument for investing time in things like smart recommendation systems, which is a big part of keeping people engaged on your site.</p>
        <h2 style="clear: both; color: #111111; font-family: 'Source Sans Pro', serif; line-height: 1.4; font-size: 1.75rem; margin-bottom: 1em; margin-top: 2em;"><span style="font-weight: 400;">Conclusion</span></h2>
        <p style="margin: 0px 0px 1.5em; color: #444444; font-family: 'Source Sans Pro', serif; font-size: 20px;">Hopefully you’ve learnt a bit about how we’re trying to tackle the education funding problem in Canada. We’re a young company trying to solve big problems so we’re always trying to learn as much as possible. If anything here is interesting to you, you should consider <a href="mailto:tomiwa@atila.ca" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">joining</a> our <a href="team" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">team</a>. If you have any advice or comments on our stack or things we should consider, we’d love to hear your thoughts in the comments or you can send me an email, <a href="mailto:tomiwa@atila.ca" style="background-color: transparent; color: #34a4f9; transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, color 0.15s ease-in-out, opacity 0.15s ease-in-out;" target="_blank">tomiwa@atila.ca</a>.</p>`
